import type { NextPage } from "next";
import Head from "next/head";
import { Button } from "@material-ui/core";

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Button variant="contained" color="primary">
				Button
			</Button>

			<h1>Ready to go!</h1>
		</div>
	);
};

export default Home;
